// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef fl_darkcfgwnd_h
#define fl_darkcfgwnd_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>
#endif
