// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "fl_darkcfgwnd.h"

static Fl_Double_Window *pDarkCfgWnd=(Fl_Double_Window *)0;

static Fl_Browser *pCategoryList=(Fl_Browser *)0;

static Fl_Browser *pOptionList=(Fl_Browser *)0;

static Fl_Text_Display *pConfigInfo=(Fl_Text_Display *)0;

static Fl_Double_Window* MakeDarkConfigWindow(int scale) {
  { pDarkCfgWnd = new Fl_Double_Window(SCALE(615), SCALE(405), $("Game Options"));
    { pCategoryList = new Fl_Browser(SCALE(2), SCALE(5), SCALE(128), SCALE(367));
      pCategoryList->type(1);
      pCategoryList->textfont(1);
    } // Fl_Browser* pCategoryList
    { pOptionList = new Fl_Browser(SCALE(135), SCALE(5), SCALE(480), SCALE(255));
      pOptionList->type(1);
    } // Fl_Browser* pOptionList
    { pConfigInfo = new Fl_Text_Display(SCALE(135), SCALE(265), SCALE(480), SCALE(106));
    } // Fl_Text_Display* pConfigInfo
    { new Fl_Button(SCALE(520), SCALE(380), SCALE(95), SCALE(25), $("OK"));
    } // Fl_Button* o
    { new Fl_Button(SCALE(405), SCALE(380), SCALE(95), SCALE(25), $("Cancel"));
    } // Fl_Button* o
    pDarkCfgWnd->set_modal();
    pDarkCfgWnd->end();
  } // Fl_Double_Window* pDarkCfgWnd
  return pDarkCfgWnd;
}
