// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "fl_mainwnd.h"

Fl_Double_Window *pMainWnd=(Fl_Double_Window *)0;

Fl_FM_List *pFMList=(Fl_FM_List *)0;

static Fl_Group *pGroupBottom=(Fl_Group *)0;

static Fl_Button *pBtnSkipFM=(Fl_Button *)0;

static Fl_FM_Return_Button *pBtnPlayFM=(Fl_FM_Return_Button *)0;

static Fl_Button *pBtnStartFM=(Fl_Button *)0;

static Fl_Group *pGroupTop=(Fl_Group *)0;

static Fl_FM_Filter_Input *pFilterName=(Fl_FM_Filter_Input *)0;

static Fl_Choice *pFilterRating=(Fl_Choice *)0;

static Fl_Choice *pFilterPrio=(Fl_Choice *)0;

static Fl_FM_Filter_Button *pFilterNotPlayed=(Fl_FM_Filter_Button *)0;

static Fl_FM_Filter_Button *pFilterCompleted=(Fl_FM_Filter_Button *)0;

static Fl_FM_Filter_Button *pFilterInProgress=(Fl_FM_Filter_Button *)0;

static Fl_FM_Filter_Button *pFilterArchived=(Fl_FM_Filter_Button *)0;

static Fl_FM_Filter_Button *pFilterNotAvail=(Fl_FM_Filter_Button *)0;

static Fl_FM_Filter_Input *pFilterRelDateFrom=(Fl_FM_Filter_Input *)0;

static Fl_FM_Filter_Input *pFilterRelDateTo=(Fl_FM_Filter_Input *)0;

static Fl_FM_TagFilter_Group *pTagFilterGroup=(Fl_FM_TagFilter_Group *)0;

static Fl_Double_Window* MakeWindow(int scale) {
  { pMainWnd = new Fl_Double_Window(SCALE(630), SCALE(380), $("Dark FM Selector"));
    { Fl_FM_List* o = pFMList = new Fl_FM_List(SCALE(5), SCALE(80), SCALE(620), SCALE(255));
      pFMList->box(FL_NO_BOX);
      pFMList->color((Fl_Color)FL_BACKGROUND2_COLOR);
      pFMList->selection_color((Fl_Color)230);
      pFMList->labeltype(FL_NORMAL_LABEL);
      pFMList->labelfont(0);
      pFMList->labelsize(SCALE(10));
      pFMList->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      pFMList->textfont(1);
      pFMList->align(FL_ALIGN_BOTTOM);
      pFMList->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(pFMList);
      pFMList->selection_color( fl_rgb_color(170,238,255) );
      o->labelsize(FL_NORMAL_SIZE-2);
    } // Fl_FM_List* pFMList
    { pGroupBottom = new Fl_Group(SCALE(5), SCALE(348), SCALE(620), SCALE(32));
      { Fl_Button* o = pBtnSkipFM = new Fl_Button(SCALE(5), SCALE(348), SCALE(120), SCALE(25), $("Skip FM"));
        pBtnSkipFM->tooltip($("Launch without FM"));
        pBtnSkipFM->shortcut(0xff1b);
        pBtnSkipFM->callback((Fl_Callback*)OnPlayOM);
        pBtnSkipFM->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        o->image(imgPlay);
        o->labeltype(IMAGETEXT_LABEL);
      } // Fl_Button* pBtnSkipFM
      { Fl_FM_Return_Button* o = pBtnPlayFM = new Fl_FM_Return_Button(SCALE(136), SCALE(348), SCALE(120), SCALE(25), $("Play FM"));
        pBtnPlayFM->tooltip($("Launch selected FM"));
        pBtnPlayFM->box(FL_UP_BOX);
        pBtnPlayFM->color((Fl_Color)FL_BACKGROUND_COLOR);
        pBtnPlayFM->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pBtnPlayFM->labeltype(FL_NORMAL_LABEL);
        pBtnPlayFM->labelfont(0);
        pBtnPlayFM->labelsize(SCALE(12));
        pBtnPlayFM->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pBtnPlayFM->callback((Fl_Callback*)OnPlayFM);
        pBtnPlayFM->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        pBtnPlayFM->when(FL_WHEN_RELEASE);
        o->image(imgPlayFM);
        o->deimage(pImgPlayFMGray);
        o->labeltype(IMAGETEXT_LABEL);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_FM_Return_Button* pBtnPlayFM
      { Fl_Button* o = pBtnStartFM = new Fl_Button(SCALE(263), SCALE(348), SCALE(120), SCALE(25), $("Start FM"));
        pBtnStartFM->tooltip($("Launch selected FM and change status to \'Playing\'"));
        pBtnStartFM->callback((Fl_Callback*)OnStartFM);
        pBtnStartFM->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        o->image(imgStartFM);
        o->deimage(pImgStartFMGray);
        o->labeltype(IMAGETEXT_LABEL);
      } // Fl_Button* pBtnStartFM
      { Fl_Button* o = new Fl_Button(SCALE(525), SCALE(348), SCALE(100), SCALE(25), $("Exit"));
        o->callback((Fl_Callback*)OnExit);
      } // Fl_Button* o
      { Fl_Group* o = new Fl_Group(SCALE(395), SCALE(348), SCALE(14), SCALE(25));
        o->hide();
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Group* o
      { Fl_FM_Config_Button* o = new Fl_FM_Config_Button(SCALE(411), SCALE(348), SCALE(44), SCALE(25));
        o->tooltip($("Options/Tasks menu"));
        o->box(FL_UP_BOX);
        o->color((Fl_Color)FL_BACKGROUND_COLOR);
        o->selection_color((Fl_Color)FL_SELECTION_COLOR);
        o->labeltype(FL_NORMAL_LABEL);
        o->labelfont(0);
        o->labelsize(SCALE(12));
        o->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        o->when(FL_WHEN_RELEASE_ALWAYS);
        o->image(imgOptions);
        o->labelsize(FL_NORMAL_SIZE);
      } // Fl_FM_Config_Button* o
      pGroupBottom->end();
    } // Fl_Group* pGroupBottom
    { pGroupTop = new Fl_Group(SCALE(5), SCALE(5), SCALE(620), SCALE(40));
      { Fl_FM_Filter_Input* o = pFilterName = new Fl_FM_Filter_Input(SCALE(5), SCALE(20), SCALE(180), SCALE(24), $("Name"));
        pFilterName->tooltip($("Only show FMs whose names contain this sub-string"));
        pFilterName->box(FL_DOWN_BOX);
        pFilterName->color((Fl_Color)FL_BACKGROUND2_COLOR);
        pFilterName->selection_color((Fl_Color)FL_SELECTION_COLOR);
        pFilterName->labeltype(FL_NORMAL_LABEL);
        pFilterName->labelfont(0);
        pFilterName->labelsize(SCALE(11));
        pFilterName->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterName->textsize(SCALE(12));
        pFilterName->callback((Fl_Callback*)OnFilterName);
        pFilterName->align(FL_ALIGN_TOP_LEFT);
        pFilterName->when(FL_WHEN_RELEASE);
        o->when(FL_WHEN_ENTER_KEY | FL_WHEN_CHANGED | FL_WHEN_RELEASE_ALWAYS);
        o->textsize(FL_NORMAL_SIZE);
      } // Fl_FM_Filter_Input* pFilterName
      { Fl_Choice* o = pFilterRating = new Fl_Choice(SCALE(195), SCALE(20), SCALE(55), SCALE(24), $("Min Rating"));
        pFilterRating->tooltip($("Show  FMs with a minimum rating of"));
        pFilterRating->down_box(FL_BORDER_BOX);
        pFilterRating->labelsize(SCALE(11));
        pFilterRating->callback((Fl_Callback*)OnFilterRating);
        pFilterRating->align(FL_ALIGN_TOP_LEFT);
        o->menu(g_mnuFiltRating);
      } // Fl_Choice* pFilterRating
      { Fl_Choice* o = pFilterPrio = new Fl_Choice(SCALE(260), SCALE(20), SCALE(55), SCALE(24), $("Min Pri"));
        pFilterPrio->tooltip($("Show  FMs with a minimum priority of"));
        pFilterPrio->down_box(FL_BORDER_BOX);
        pFilterPrio->labelsize(SCALE(11));
        pFilterPrio->callback((Fl_Callback*)OnFilterPriority);
        pFilterPrio->align(FL_ALIGN_TOP_LEFT);
        o->menu(g_mnuFiltPrio);
      } // Fl_Choice* pFilterPrio
      { Fl_Box* o = new Fl_Box(SCALE(322), SCALE(6), SCALE(45), SCALE(15), $("Status"));
        o->labelsize(SCALE(11));
        o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      } // Fl_Box* o
      { Fl_FM_Filter_Button* o = pFilterNotPlayed = new Fl_FM_Filter_Button(SCALE(325), SCALE(20), SCALE(30), SCALE(24));
        pFilterNotPlayed->tooltip($("Show FMs that haven\'t been completed or currently in progress"));
        pFilterNotPlayed->type(1);
        pFilterNotPlayed->box(FL_UP_BOX);
        pFilterNotPlayed->color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterNotPlayed->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterNotPlayed->labeltype(FL_NORMAL_LABEL);
        pFilterNotPlayed->labelfont(0);
        pFilterNotPlayed->labelsize(SCALE(14));
        pFilterNotPlayed->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterNotPlayed->callback((Fl_Callback*)OnFilterToggle, (void*)(1));
        pFilterNotPlayed->align(FL_ALIGN_CENTER);
        pFilterNotPlayed->when(FL_WHEN_RELEASE);
        o->image(imgNotPlayed);
        o->deimage(imgNotPlayed);
        o->down_color(TOGBTN_DN_CLR);
      } // Fl_FM_Filter_Button* pFilterNotPlayed
      { Fl_FM_Filter_Button* o = pFilterCompleted = new Fl_FM_Filter_Button(SCALE(354), SCALE(20), SCALE(30), SCALE(24));
        pFilterCompleted->tooltip($("Show completed FMs"));
        pFilterCompleted->type(1);
        pFilterCompleted->box(FL_UP_BOX);
        pFilterCompleted->color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterCompleted->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterCompleted->labeltype(FL_NORMAL_LABEL);
        pFilterCompleted->labelfont(0);
        pFilterCompleted->labelsize(SCALE(14));
        pFilterCompleted->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterCompleted->callback((Fl_Callback*)OnFilterToggle, (void*)(2));
        pFilterCompleted->align(FL_ALIGN_CENTER);
        pFilterCompleted->when(FL_WHEN_RELEASE);
        o->image(imgCheck);
        o->deimage(pImgCheckGray);
        o->down_color(TOGBTN_DN_CLR);
      } // Fl_FM_Filter_Button* pFilterCompleted
      { Fl_FM_Filter_Button* o = pFilterInProgress = new Fl_FM_Filter_Button(SCALE(383), SCALE(20), SCALE(30), SCALE(24));
        pFilterInProgress->tooltip($("Show FMs with a playthrough in progress"));
        pFilterInProgress->type(1);
        pFilterInProgress->box(FL_UP_BOX);
        pFilterInProgress->color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterInProgress->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterInProgress->labeltype(FL_NORMAL_LABEL);
        pFilterInProgress->labelfont(0);
        pFilterInProgress->labelsize(SCALE(14));
        pFilterInProgress->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterInProgress->callback((Fl_Callback*)OnFilterToggle, (void*)(3));
        pFilterInProgress->align(FL_ALIGN_CENTER);
        pFilterInProgress->when(FL_WHEN_RELEASE);
        o->image(imgProgress);
        o->deimage(pImgProgressGray);
        o->down_color(TOGBTN_DN_CLR);
      } // Fl_FM_Filter_Button* pFilterInProgress
      { Fl_Box* o = new Fl_Box(SCALE(420), SCALE(6), SCALE(35), SCALE(15), $("Avail"));
        o->labelsize(SCALE(11));
        o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      } // Fl_Box* o
      { Fl_FM_Filter_Button* o = pFilterArchived = new Fl_FM_Filter_Button(SCALE(423), SCALE(20), SCALE(30), SCALE(24));
        pFilterArchived->tooltip($("Show archived FMs that aren\'t installed"));
        pFilterArchived->type(1);
        pFilterArchived->box(FL_UP_BOX);
        pFilterArchived->color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterArchived->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterArchived->labeltype(FL_NORMAL_LABEL);
        pFilterArchived->labelfont(0);
        pFilterArchived->labelsize(SCALE(14));
        pFilterArchived->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterArchived->callback((Fl_Callback*)OnFilterToggle, (void*)(5));
        pFilterArchived->align(FL_ALIGN_CENTER);
        pFilterArchived->when(FL_WHEN_RELEASE);
        o->image(imgArchived);
        o->deimage(pImgArchivedGray);
        o->down_color(TOGBTN_DN_CLR);
      } // Fl_FM_Filter_Button* pFilterArchived
      { Fl_FM_Filter_Button* o = pFilterNotAvail = new Fl_FM_Filter_Button(SCALE(452), SCALE(20), SCALE(30), SCALE(24));
        pFilterNotAvail->tooltip($("Show FMs that aren\'t available"));
        pFilterNotAvail->type(1);
        pFilterNotAvail->box(FL_UP_BOX);
        pFilterNotAvail->color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterNotAvail->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        pFilterNotAvail->labeltype(FL_NORMAL_LABEL);
        pFilterNotAvail->labelfont(0);
        pFilterNotAvail->labelsize(SCALE(14));
        pFilterNotAvail->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterNotAvail->callback((Fl_Callback*)OnFilterToggle, (void*)(4));
        pFilterNotAvail->align(FL_ALIGN_CENTER);
        pFilterNotAvail->when(FL_WHEN_RELEASE);
        o->image(imgNotAvail);
        o->deimage(pImgNotAvailGray);
        o->down_color(TOGBTN_DN_CLR);
      } // Fl_FM_Filter_Button* pFilterNotAvail
      { Fl_FM_Filter_Input* o = pFilterRelDateFrom = new Fl_FM_Filter_Input(SCALE(491), SCALE(20), SCALE(25), SCALE(24), $("Rel. Year"));
        pFilterRelDateFrom->tooltip($("Show FMs released from year (YY), leave empty for no lower limit"));
        pFilterRelDateFrom->type(2);
        pFilterRelDateFrom->box(FL_DOWN_BOX);
        pFilterRelDateFrom->color((Fl_Color)FL_BACKGROUND2_COLOR);
        pFilterRelDateFrom->selection_color((Fl_Color)FL_SELECTION_COLOR);
        pFilterRelDateFrom->labeltype(FL_NORMAL_LABEL);
        pFilterRelDateFrom->labelfont(0);
        pFilterRelDateFrom->labelsize(SCALE(11));
        pFilterRelDateFrom->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterRelDateFrom->textsize(SCALE(12));
        pFilterRelDateFrom->callback((Fl_Callback*)OnFilterRelFrom);
        pFilterRelDateFrom->align(FL_ALIGN_TOP_LEFT);
        pFilterRelDateFrom->when(FL_WHEN_ENTER_KEY);
        o->maximum_size(2);
        o->when(FL_WHEN_ENTER_KEY | FL_WHEN_RELEASE);
        o->textsize(FL_NORMAL_SIZE);
      } // Fl_FM_Filter_Input* pFilterRelDateFrom
      { Fl_FM_Filter_Input* o = pFilterRelDateTo = new Fl_FM_Filter_Input(SCALE(527), SCALE(20), SCALE(25), SCALE(24), $("-"));
        pFilterRelDateTo->tooltip($("Show FMs released up to and including year (YY), leave empty for no upper lim\
it"));
        pFilterRelDateTo->type(2);
        pFilterRelDateTo->box(FL_DOWN_BOX);
        pFilterRelDateTo->color((Fl_Color)FL_BACKGROUND2_COLOR);
        pFilterRelDateTo->selection_color((Fl_Color)FL_SELECTION_COLOR);
        pFilterRelDateTo->labeltype(FL_NORMAL_LABEL);
        pFilterRelDateTo->labelfont(0);
        pFilterRelDateTo->labelsize(SCALE(11));
        pFilterRelDateTo->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        pFilterRelDateTo->textsize(SCALE(12));
        pFilterRelDateTo->callback((Fl_Callback*)OnFilterRelTo);
        pFilterRelDateTo->align(FL_ALIGN_LEFT);
        pFilterRelDateTo->when(FL_WHEN_ENTER_KEY);
        o->maximum_size(2);
        o->when(FL_WHEN_ENTER_KEY | FL_WHEN_RELEASE);
        o->textsize(FL_NORMAL_SIZE);
      } // Fl_FM_Filter_Input* pFilterRelDateTo
      { Fl_Group* o = new Fl_Group(SCALE(557), SCALE(5), SCALE(4), SCALE(40));
        o->hide();
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Group* o
      { Fl_Button* o = new Fl_Button(SCALE(562), SCALE(20), SCALE(30), SCALE(24));
        o->tooltip($("Refresh list to apply filter and sorting to status changes etc."));
        o->callback((Fl_Callback*)OnRefreshFilters);
        o->image(imgRefresh);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(SCALE(595), SCALE(20), SCALE(30), SCALE(24));
        o->tooltip($("Reset to default filter settings"));
        o->callback((Fl_Callback*)OnResetFilters);
        o->image(imgResetFilters);
      } // Fl_Button* o
      pGroupTop->end();
    } // Fl_Group* pGroupTop
    { Fl_FM_TagFilter_Group* o = pTagFilterGroup = new Fl_FM_TagFilter_Group(SCALE(5), SCALE(50), SCALE(620), SCALE(21));
      pTagFilterGroup->box(FL_FLAT_BOX);
      pTagFilterGroup->color((Fl_Color)16);
      pTagFilterGroup->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      pTagFilterGroup->labeltype(FL_NORMAL_LABEL);
      pTagFilterGroup->labelfont(0);
      pTagFilterGroup->labelsize(SCALE(14));
      pTagFilterGroup->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      pTagFilterGroup->align(FL_ALIGN_TOP);
      pTagFilterGroup->when(FL_WHEN_RELEASE);
      o->color( fl_rgb_color(226,226,217) );
      pTagFilterGroup->end();
    } // Fl_FM_TagFilter_Group* pTagFilterGroup
    pMainWnd->size_range(SCALE(630), SCALE(380));
    pMainWnd->callback((Fl_Callback*)OnClose);
    pMainWnd->end();
  } // Fl_Double_Window* pMainWnd
  return pMainWnd;
}
