// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef fl_taged_h
#define fl_taged_h
#include <FL/Fl.H>
extern Fl_FM_TagEd_Window *pTagEdWnd;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Button.H>
extern void OnTagEdViewInfoFile(Fl_Button*, void*);
#include <FL/Fl_Box.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Check_Button.H>
extern void OnTagEdAddTag(Fl_Button*, void*);
extern Fl_Button *pTagEdAddTag;
extern void OnTagPreset(Fl_Choice*, void*);
extern Fl_FM_Tag_Group *pTagEdGroup;
#include <FL/Fl_Text_Editor.H>
extern void OnCancelTagEditor(Fl_Button*, void*);
extern void OnOkTagEditor(Fl_Button*, void*);
#endif
